{% set version = "0.10" %}

package:
  name: zbar
  version: {{ version }}

source:
  url: http://sourceforge.net/projects/zbar/files/zbar/{{ version }}/zbar-{{ version }}.tar.bz2
  sha256: 234efb39dbbe5cef4189cc76f37afbe3cfcfb45ae52493bfe8e191318bdbadc6
  patches:
    - 0001-Add-cstddef-header-to-zbar.h-for-NULL.patch

build:
  number: 1001
  skip: True  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make    # [unix]
  host:
    - libjpeg-turbo
  run:
    - libjpeg-turbo

test:
  commands:
    - bash -c "test -f $PREFIX/lib/libzbar.a"  # [unix]
    - bash -c "test -f $PREFIX/lib/libzbar.so"  # [linux]
    - bash -c "test -f $PREFIX/lib/libzbar.dylib"  # [osx]
    - bash -c "test -d $PREFIX/include/zbar && test -f $PREFIX/include/zbar/ImageScanner.h"  # [unix]

about:
  home: http://zbar.sourceforge.net/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: 'Zbar barcode reader library'

  description: |
    ZBar is an open source software suite for reading bar codes from various
    sources, such as video streams, image files and raw intensity sensors. It
    supports many popular symbologies (types of bar codes) including
    EAN-13/UPC-A, UPC-E, EAN-8, Code 128, Code 39, Interleaved 2 of 5 and QR
    Code.
  dev_url: https://github.com/ZBar/ZBar
  doc_url: https://sourceforge.net/projects/zbar/

extra:
  recipe-maintainers:
    # Stopped exiting
    # - kdmurray91
    # Just adding myself here to help from time to time
    - hmaarrfk
