schema_version: 1

context:
  version: 0.23.93

package:
  name: zbar
  version: ${{ version }}

source:
  url: https://linuxtv.org/downloads/zbar/zbar-${{ version }}.tar.bz2
  sha256: 83be8f85fc7c288fd91f98d52fc55db7eedbddcf10a83d9221d7034636683fa0
#  patches:
#    - 0001-Add-cstddef-header-to-zbar.h-for-NULL.patch

build:
  number: 3
  skip: win

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make
    - python
  host:
    - python
    - setuptools
    - gettext
    - libjpeg-turbo
  run:
    - python
    - libjpeg-turbo

tests:
  - script:
      - if: unix
        then: bash -c "test -f $PREFIX/lib/libzbar.a"
      - if: linux
        then: bash -c "test -f $PREFIX/lib/libzbar.so"
      - if: osx
        then: bash -c "test -f $PREFIX/lib/libzbar.dylib"
      - if: unix
        then: bash -c "test -d $PREFIX/include/zbar && test -f $PREFIX/include/zbar/ImageScanner.h"

about:
  license: LGPL-2.1-only
  license_file: COPYING
  summary: Zbar barcode reader library
  description: |
    ZBar is an open source software suite for reading bar codes from various
    sources, such as video streams, image files and raw intensity sensors. It
    supports many popular symbologies (types of bar codes) including
    EAN-13/UPC-A, UPC-E, EAN-8, Code 128, Code 39, Interleaved 2 of 5 and QR
    Code.
  homepage: https://github.com/mchehab/zbar
  repository: https://github.com/mchehab/zbar
  documentation: https://sourceforge.net/projects/zbar/

extra:
  recipe-maintainers:
    - jan-janssen
    # Stopped exiting
    # - kdmurray91
    # Just adding myself here to help from time to time
    - hmaarrfk
