# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "pUtc49iKc/SbbblK+XQh/CXDju6iTPJWuZMbQuycZoqdVw1xxtPqhuXYYXxI50zRvIxAe1NsMzxmTpQosemaAf1OBEeIiqAuamXpsjehCgfWzinwuCej/5AVSdYQCAls3fG1dVagbm8GlW3L8hX8zNjEXNvvNJjI+9gk6PhQv2ls1S+C2ghqwB5JZ4hLwgAH8sDAWF64AdQGlS4Z9mtadscNBQW+qmTuSkZApEz/7SdsTxCs88FqND7cLLC3JUfYrTYFO5k4BObyqLY0mY8JmrzYZQyf0Q6VizJm26uqEmjGug8GQ6RdwT5BbyCExafV4riXEKTwF+YUK9Rm9GL2uOAr0CgStIYmiyATC2HHFGL8kLIvk0EZtAv83kpbou2bOaHweCRdvLmsRO3oypEgIrGxxoVM0M31fRL1pMLAkxNcbdQ9ChXzNFU2pMvGI7k24beJY067LuYt5sQjh7ph8YUEQPkP8VCa21YO8OdkPq4UyxHUZEjvuroDUXu5PR7hhcOaAzjfZsyW23qaCy7ELXN3WTzcqMhcIFnE17P7WwmMTDR+47f5Vy9wyQDM4Vd9ViOae/S/Vahyd08xPKFL1sNzQsbpZBcfQxfPGC1JJQI8z9QwsxYvNgx92AAK6pE9CLiqfoxCVkxHf5K2IFgvgZKFIJ2fVspgTYw8mXKOfzg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
