appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pUtc49iKc/SbbblK+XQh/CXDju6iTPJWuZMbQuycZoqdVw1xxtPqhuXYYXxI50zRvIxAe1NsMzxmTpQosemaAf1OBEeIiqAuamXpsjehCgfWzinwuCej/5AVSdYQCAls3fG1dVagbm8GlW3L8hX8zNjEXNvvNJjI+9gk6PhQv2ls1S+C2ghqwB5JZ4hLwgAH8sDAWF64AdQGlS4Z9mtadscNBQW+qmTuSkZApEz/7SdsTxCs88FqND7cLLC3JUfYrTYFO5k4BObyqLY0mY8JmrzYZQyf0Q6VizJm26uqEmjGug8GQ6RdwT5BbyCExafV4riXEKTwF+YUK9Rm9GL2uOAr0CgStIYmiyATC2HHFGL8kLIvk0EZtAv83kpbou2bOaHweCRdvLmsRO3oypEgIrGxxoVM0M31fRL1pMLAkxNcbdQ9ChXzNFU2pMvGI7k24beJY067LuYt5sQjh7ph8YUEQPkP8VCa21YO8OdkPq4UyxHUZEjvuroDUXu5PR7hhcOaAzjfZsyW23qaCy7ELXN3WTzcqMhcIFnE17P7WwmMTDR+47f5Vy9wyQDM4Vd9ViOae/S/Vahyd08xPKFL1sNzQsbpZBcfQxfPGC1JJQI8z9QwsxYvNgx92AAK6pE9CLiqfoxCVkxHf5K2IFgvgZKFIJ2fVspgTYw8mXKOfzg=}
conda_forge_output_validation: true
