travis:
  secure:
    BINSTAR_TOKEN: AQXlY1ENmg+Wf2bCfl2Pf9TmVNEwJeJS+7yPDspGZ1MLQoB/bv1W5FOnbHKFA7vS80JR1AiIT9cMLkhQYqWW+XAOcEBjC2EkPlsUYxv3K07DTqcrr4qRKWyyFYsjcXygSyGV2qKV1IylPlOquB1bBguBJ3vVwpMTuQxEm1zG2aXehs53dHObFGb8i2h9nyopDNE1+0mi1zZ+DzStVmfz0jwu2pqhvZIXPfXcmGaPczcEKf5eNLKxJH2Bj0h+xP3SNb4g5aN+v+4FhhBNeSK5KsvcYWOyVR7QYftgWhLNS3Nkgca7KQJeulN76UswNi8BOhWwqnZ8x5khLpgYYPsJnOCYpUxmyarlrA5pPmTOELc6Q4TBgsG03WOK7FEz+LLJWc9bYlUACHmU2puLkgt1hymYbXZN4gpymnIEfEzL5clH2moz5dTAD9H3fxgwNxHN31a8fDTSGhJ5MHIimdX1lGxgbhG6pX/O6m0bSNAXhP4ROYECOPkeYHl4sdUWxTaE8NheK6L+270ELkKPYgklbtFuq/qmJXiAygdpG/sTmqARn6vft6AyeyUuQatt18hJP5pAxOs+PTKHV74t0lDa/xDZE73y6BC6eRaR5c0ZY9iyt2YpIP4C6rwRCf2FIvr51mqUlBgjdPa5ao6VI5lS6FtMCdnsVTz9RzJiJL4DkY4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
